# Generated by Django 3.1.2 on 2021-07-28 08:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_ou_projet', models.BooleanField(default=True)),
                ('date_debut_stage', models.DateField()),
                ('date_fin_stage', models.DateField()),
                ('intitule_stage', models.CharField(default='', max_length=200)),
                ('societe_stage', models.CharField(default='', max_length=200)),
                ('secteur_societe', models.CharField(default='', max_length=200)),
                ('ville_societe', models.CharField(default='', max_length=200)),
                ('pays_societe', models.CharField(default='', max_length=200)),
                ('details_add_societe', models.CharField(blank=True, max_length=200)),
                ('encadrant', models.CharField(max_length=200)),
                ('email_encadrant', models.EmailField(max_length=254)),
                ('telephone_encadrant', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('lien_rapport', models.URLField()),
                ('rapport_confidentiel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('code_etudiant', models.IntegerField()),
                ('prenom', models.CharField(default='', max_length=200)),
                ('nom', models.CharField(default='', max_length=200)),
                ('email_perso', models.EmailField(max_length=254)),
                ('email_pro', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('filiere', models.CharField(default='', max_length=200)),
                ('promotion', models.DateField()),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('prenom', models.CharField(default='', max_length=200)),
                ('nom', models.CharField(default='', max_length=200)),
                ('email_perso', models.EmailField(max_length=254)),
                ('email_pro', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('departement', models.CharField(default='', max_length=200)),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(default='', max_length=200)),
                ('rapports', models.ManyToManyField(to='main_app.Rapport')),
            ],
        ),
        migrations.CreateModel(
            name='Insertion',
            fields=[
                ('cursus_post_ensam', models.CharField(default='', max_length=200)),
                ('univ', models.CharField(default='', max_length=200)),
                ('pays_univ', models.CharField(default='', max_length=200)),
                ('nature_formation', models.CharField(default='', max_length=200)),
                ('intit_formation', models.CharField(blank=True, default='', max_length=200)),
                ('intit_poste', models.CharField(blank=True, default='', max_length=200)),
                ('societe', models.CharField(default='', max_length=200)),
                ('ville_societe', models.CharField(default='', max_length=200)),
                ('date_integration', models.DateField()),
                ('fk_etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='rapport',
            name='fk_etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.etudiant'),
        ),
    ]
