# Generated by Django 3.1.2 on 2021-07-20 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_ou_projet', models.BooleanField(default=True)),
                ('date_debut_stage', models.DateField()),
                ('date_fin_stage', models.DateField()),
                ('intitulé_stage', models.CharField(default='', max_length=200)),
                ('société_stage', models.CharField(default='', max_length=200)),
                ('secteur_société', models.CharField(default='', max_length=200)),
                ('ville_société', models.CharField(default='', max_length=200)),
                ('pays_société', models.CharField(default='', max_length=200)),
                ('détails_add_société', models.CharField(default='', max_length=200)),
                ('encadrant', models.CharField(max_length=200)),
                ('email_encadrant', models.EmailField(max_length=254)),
                ('téléphone_encadrant', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('lien_rapport', models.URLField()),
                ('rapport_confidentiel', models.BooleanField(default=True)),
            ],
        ),
    ]
