# Generated by Django 3.1.2 on 2021-08-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='resume_rapport',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='rapport',
            name='type_rapport',
            field=models.CharField(default='', max_length=200),
        ),
    ]
