# Generated by Django 3.1.2 on 2021-07-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport',
            old_name='détails_add_société',
            new_name='details_add_societe',
        ),
        migrations.RenameField(
            model_name='rapport',
            old_name='intitulé_stage',
            new_name='intitule_stage',
        ),
        migrations.RenameField(
            model_name='rapport',
            old_name='pays_société',
            new_name='pays_societe',
        ),
        migrations.RenameField(
            model_name='rapport',
            old_name='secteur_société',
            new_name='secteur_societe',
        ),
        migrations.RenameField(
            model_name='rapport',
            old_name='société_stage',
            new_name='societe_stage',
        ),
        migrations.RenameField(
            model_name='rapport',
            old_name='téléphone_encadrant',
            new_name='telephone_encadrant',
        ),
        migrations.RenameField(
            model_name='rapport',
            old_name='ville_société',
            new_name='ville_societe',
        ),
    ]
