# Generated by Django 3.1.2 on 2021-07-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='date_integration',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='nature_formation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='pays_univ',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='societe',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='univ',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='ville_societe',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
