# Generated by Django 3.1.2 on 2021-08-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='code_etudiant',
            field=models.CharField(default='', max_length=200),
        ),
    ]
