# Generated by Django 3.1.2 on 2021-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='promotion',
            field=models.CharField(default='', max_length=4),
        ),
    ]
