# Generated by Django 3.1.2 on 2021-09-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='fk_encadrant_univ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.professeur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapport',
            name='valid_encadrant',
            field=models.BooleanField(default=False),
        ),
    ]
