# Generated by Django 3.1.2 on 2021-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='détails_add_société',
            field=models.CharField(max_length=200),
        ),
    ]
