# Generated by Django 3.1.2 on 2021-09-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210924_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='fk_encadrant_univ',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.professeur'),
        ),
    ]
