# Generated by Django 3.1.2 on 2021-08-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210822_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='code_etudiant',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
