# Generated by Django 3.1.2 on 2021-07-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210728_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='fk_id_user',
            new_name='fk_user',
        ),
        migrations.RenameField(
            model_name='insertion',
            old_name='fk_code_etudiant',
            new_name='fk_etudiant',
        ),
        migrations.RenameField(
            model_name='professeur',
            old_name='fk_id_user',
            new_name='fk_user',
        ),
        migrations.RenameField(
            model_name='rapport',
            old_name='fk_id_etudiant',
            new_name='fk_etudiant',
        ),
    ]
