# Generated by Django 3.1.2 on 2021-07-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210728_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='date_integration',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='intit_formation',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='intit_poste',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='nature_formation',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='pays_univ',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='societe',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='univ',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='ville_societe',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
