# Generated by Django 3.1.2 on 2021-07-20 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210720_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='détails_add_société',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='téléphone_encadrant',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
