# Generated by Django 3.1.2 on 2021-07-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210720_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(default='', max_length=200)),
                ('rapports', models.ManyToManyField(to='main_app.Rapport')),
            ],
        ),
    ]
