# Generated by Django 3.1.2 on 2021-09-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210924_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='valid_encadrant',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
