# Generated by Django 3.1.2 on 2021-08-22 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_etudiant_nom_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='fichier_rapport',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
