# Generated by Django 3.1.2 on 2021-08-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210728_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='encadrant',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='pays_societe',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='secteur_societe',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='societe_stage',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='ville_societe',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
