# Generated by Django 3.1.2 on 2021-07-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_motcle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('type_user', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
