# Generated by Django 3.1.2 on 2021-07-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210728_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insertion',
            old_name='pays_univ',
            new_name='pays',
        ),
        migrations.RenameField(
            model_name='insertion',
            old_name='ville_societe',
            new_name='ville',
        ),
    ]
