# Generated by Django 3.1.2 on 2021-08-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210822_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='resume_rapport',
            field=models.CharField(blank=True, default=None, max_length=3000, null=True),
        ),
    ]
