# Generated by Django 3.1.2 on 2021-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210730_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='pays',
            field=models.CharField(default=66, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insertion',
            name='ville',
            field=models.CharField(default=77, max_length=200),
            preserve_default=False,
        ),
    ]
