# Generated by Django 3.1.2 on 2021-08-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210801_1441'),
        ('main_app', '0005_auto_20210801_1220'),
    ]

    operations = [
    ]
