# Generated by Django 3.1.2 on 2021-07-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='type_user',
            field=models.CharField(default='', max_length=1),
        ),
    ]
