# Generated by Django 3.1.2 on 2021-08-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210823_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='nom_prenom',
            field=models.CharField(default='', max_length=200),
        ),
    ]
