# Generated by Django 3.1.2 on 2021-09-08 16:19

import django.core.validators
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_professeur_nom_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_form', models.CharField(default='', max_length=200)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_debut_stage',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_fin_stage',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='fichier_rapport',
            field=models.FileField(default='', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.DeleteModel(
            name='MotCle',
        ),
    ]
